### ISSUE TITLE
Guidance on the request URI structure needed?

### ISSUE THREAD

**Issue by tlodderstedt** [oauthstuff/draft-oauth-par#1]
BC QUESTION: should there some more guidance provided on or requirements around the structure of the URI value? For example it could use the RFC6755 subnamespace and registry and be of the form urn:ietf:params:oauth:request_uri:<<random-part>>, which gives a clear indication of what it is and would keep people from inventing their own URIs.

**Comment by tlodderstedt** [comment]
Filip Skokan: I think implementers should be free to either use their own URIs (gives them flexibility), but also have the option to use a registered urn: subnamespace as Brian suggested.

**Comment by tlodderstedt** [comment]
BC: RFC6755 is arguably one of the most important and impactful documents ever written.

**Comment by b---c** [comment]
using a string representation of a UUID as a URN per https://tools.ietf.org/html/rfc4122#section-3 might also be an option to mention or use in the examples

**Comment by b---c** [comment]
thread on the WG mailing list looks to be leaning towards providing some options/guidance but not mandating https://mailarchive.ietf.org/arch/msg/oauth/tb8Czp7saa1QUEf_ybjIWQiXPWs/

**Comment by b---c** [comment]
PR #48 provides some more options/guidance on the request URI value including urn:ietf:params:oauth:request_uri: or a UUID as a URN per RFC4122 but ultimately still leaves it up to the AS

**Comment by b---c** [comment]
PR #48 was merged and this should/will be in -02
