### ISSUE TITLE
Explicitly Disallow `request_uri`

### ISSUE THREAD

**Issue by jricher** [oauthstuff/draft-oauth-par#17]
It doesn't make any sense for a client to pre-register a request with a `request_uri` as one of its parameters and receive a `request_uri` as the result. Disallowing this explicitly will allow authorization servers to simplify processing requirements at the new endpoint.

**Comment by panva** [comment]
@jricher 

> The request_uri authorization request parameter MUST NOT be provided

#6 put this in

**Comment by jricher** [comment]
Seems like an afterthought as currently worded, but the requirement's there. Closing the issue, thanks.
