### ISSUE TITLE
Clarify that public clients are allowed

### ISSUE THREAD

**Issue by vdzhuvinov** [oauthstuff/draft-oauth-par#22]
The current 00 version is ambiguous about public clients:

>   The AS MUST process the request as follows:
>   1.  The AS MUST authenticate the client in same way as at the token endpoint.

**Comment by b---c** [comment]
Given that public clients (using 'none') can "authenticate" to the token endpoint and the text quoted below is earlier in the PAR draft, I've kinda felt that the wording in the draft was okay. But I realize it's an area of confusion and even contention. Do you have suggestion(s) for what would be more clear?  

> The rules for client authentication as defined in [@!RFC6749] for token endpoint requests, including the applicable authentication methods, apply for the pushed authorization request endpoint as well. If applicable, the token_endpoint_auth_method client metadata parameter indicates the registered authentication method for the client to use when making direct requests to the authorization server, including requests to the pushed authorization endpoint.

**Comment by vdzhuvinov** [comment]
I have these two suggestions:

"If the client is confidential, the AS MUST authenticate it in the same way as at the token endpoint."

or 

"The AS MUST authenticate a confidential client in the same way as at the token endpoint."

**Comment by b---c** [comment]
Thanks @vdzhuvinov, I think I'll go w/ the 2nd one.

**Comment by b---c** [comment]
done with 1e63011
