### ISSUE TITLE
Relaying authZ error codes

### ISSUE THREAD

**Issue by vdzhuvinov** [oauthstuff/draft-oauth-par#23]
The PAR endpoint accepts authZ requests, pre-processes them and returns success (201) or an error.

When we started implementing PAR I realised there is no specified way to return the usual authZ error codes, with optional error_description and error_uri:

https://tools.ietf.org/html/rfc6749#section-4.1.2.1

These error details can help developers debug their requests. If a PAR implementation uses the existing authZ endpoint to process the request as much as possible, and only a HTTP status code is returned (potentially conflating several types of error), that helpful information is lost.

I'd like to suggest an update to section 2.3 - that in case of an authZ error the AS should include an URL-encoded body with an error code, etc, as specified in RFC 6749.

This then raises the question what to do for the class of errors that don't result in a redirection back to the client.

> If the request fails due to a missing, invalid, or mismatching redirection URI, or if the client identifier is missing or invalid, the authorization server SHOULD inform the resource owner of the error and MUST NOT automatically redirect the user-agent to the invalid redirection URI.

I'm not sure what a good solution for that would be. Define error codes for invalid redirection URI and invalid client_id, leave the response body out, or leave it up to the AS decide?

**Comment by tlodderstedt** [comment]
I would argue the AS cannot redirect back in case of invalid client_id or redirect_uri since this posses the threat of an open redirector. In case of PAR, this threat does not exist, so returning an error (code tbd) is possible and makes sense.

**Comment by vdzhuvinov** [comment]
I second that.

I was actually wondering whether it's worth complicating the PAR spec with defining error codes. 

Suitable error codes could be:

* invalid_redirect_uri
* invalid_client_id

**Comment by vdzhuvinov** [comment]
Or, use the existing `invalid_client` code, which signifies failed client authentication at the token endpoint, to also include the condition of an invalid client_id.

https://tools.ietf.org/html/rfc6749#section-5.2

Then we only have `invalid_redirect_uri` to specify as new error code.

**Comment by tlodderstedt** [comment]
sounds reasonable to me

**Comment by tlodderstedt** [comment]
@vdzhuvinov please have a look https://github.com/oauthstuff/draft-oauth-par/pull/26

**Comment by tlodderstedt** [comment]
@vdzhuvinov can we close this issue?

**Comment by vdzhuvinov** [comment]
Thanks for the PR! I will suggest an edit to clarify the types of possible error codes, also that OAuth extensions may introduce new ones. OIDC for instance may also introduce some here. I'll check that.

**Comment by tlodderstedt** [comment]
thanks. I would like to publish the draft before the end of the week (IETF-106 cut off date is next Monday).

**Comment by vdzhuvinov** [comment]
@tlodderstedt  Please, check PR #31

**Comment by tlodderstedt** [comment]
looks good
