### ISSUE TITLE
No dedicated Mix-Up prevention needed with PAR

### ISSUE THREAD

**Issue by tlodderstedt** [oauthstuff/draft-oauth-par#25]
@danielfett came up with the feeling that PAR (for confidential clients) would not be vulnerable to Mix-Up. We need to analyze this and, if true, document this as benefit and in the security considerations.

It could be beneficially to spend a section on the changes implied by PAR to the OAuth trust model.

**Comment by danielfett** [comment]
PAR does not prevent mix-up, see: https://danielfett.de/2020/05/04/mix-up-revisited/
