### ISSUE TITLE
confused over request validation at par endpoint

### ISSUE THREAD

**Issue by jogu** [oauthstuff/draft-oauth-par#27]
I don't entirely understand this text in the current master version:

> The AS MUST validate the request the same way as at the authorization endpoint. For example, the authorization server checks whether the redirect URI matches one of the redirect URIs configured for the client_id. It MAY also check whether the client is authorized for the scope for which it is requesting access. This validation allows the authorization server to refuse unauthorized or fraudulent requests early.

In particular the 'MUST' and the 'MAY' seem to conflict, as [in normal plain oauth] the AS's authorization endpoint is required to check whether scope is valid for the client. Does 'validate' have some narrower definition that means a check if the scope is valid for that client is skipped?

Or was the intended reading "*if* the AS validates the request, it must do so in the same way it would at the authorization endpoint" (and if that's the case, I'm still not entirely sure what the intent of the 'MAY' part is).

**Comment by tlodderstedt** [comment]
I made it a MUST
