### ISSUE TITLE
Register invalid_redirect_uri in the OAuth Extensions Error Registry

### ISSUE THREAD

**Issue by vdzhuvinov** [oauthstuff/draft-oauth-par#30]
http://www.iana.org/assignments/oauth-parameters/oauth-parameters.xhtml#extensions-error

**Comment by tlodderstedt** [comment]
seems invalid_request_uri has already been registered bei OIDC

However, it also seems the registrations are qualified by the endpoint as "Usage Location". This means we need to register ALL errors again?

**Comment by vdzhuvinov** [comment]
My suggestion is to register invalid_client and invalid_redirect_uri only and clearly state in the spec that all other error codes will be those from 4.1.2.1 and 4.2.2.1 of RFC 6749 and OAuth extensions to the authZ request.

I.e. argue that "Usage Location" for those codes is still the authZ request / endpoint.

I hope this will make sense :)

**Comment by tlodderstedt** [comment]
we will see :-)

**Comment by b---c** [comment]
I'm really wondering if it's worth it to have invalid_redirect_uri defined and registered. The same info can be conveyed to the client with the invalid_request code and an error_description that says the redirect_uri isn't okay. And it seems very unlikely that a client will make some sort of programatic fix to get past a invalid_redirect_uri. I think all that's really needed is to convey the error and some info for troubleshooting.

**Comment by vdzhuvinov** [comment]
> The same info can be conveyed to the client with the invalid_request code and an error_description that says the redirect_uri isn't okay

+1, this simplifies the spec!

**Comment by tlodderstedt** [comment]
closing issue since additional error code was just removed from draft
