### ISSUE TITLE
Timing of Request Validation

### ISSUE THREAD

**Issue by TakahikoKawasaki** [oauthstuff/draft-oauth-par#38]
One requirement in "2.1. Request" says as follows.

> The AS MUST validate the request in the same way as at the authorization endpoint.

I think we should change this requirement to something like:

> The AS SHOULD validate the request in the same way as at the authorization endpoint. Requirements that are not validated when the request URI is registered MUST be validated by the time or at the time when the request URI is used.

in order to make the requirement more realistic. Otherwise, I'm afraid that the WG would have to check carefully, **for each known request parameter**, whether validation can be performed at the pushed authorization request endpoint with the same meaning and the same context as at the authorization endpoint.

At least I wouldn't be able to be so sure that all validation steps at the authorization endpoint can be performed at the pushed authorization request endpoint until feasibility check is done for each known request parameter, and I guess other developers would feel the same to some extent.

**Comment by tlodderstedt** [comment]
I basically agree with your proposal. Why do you think the AS cannot validate any requests parameter? I assume that, im case of products like yours, the AS offers a SPI so custom logic can be plugged into PAR processing.

**Comment by panva** [comment]
Obviously we can’t evaluate some parameters in terms of their value being satisfied (e.g. acr_values, max age) due to lack of a session context. 

But one should be able to validate parameter values in the sense that the request is syntactically correct (e.g. max age is not negative, acr and prompt has known values, etc...)

That being said i agree the language may be a source of contention and some confusion.

**Comment by jogu** [comment]
>  I assume that, im case of products like yours, the AS offers a SPI so custom logic can be plugged into PAR processing.

Yes, but this then requires people to customise both the PAR endpoint and the authorisation endpoint. Existing plugins that do validation at the Authorization Endpoint will often assume that additional context is available, including (but not limited to) the end user's IP address, session cookies and user identity.

(This comment is intended to be vendor neutral.)

**Comment by jogu** [comment]
re: the suggest text, I'm not sure I'd be entirely happy with this:

> Requirements that are not validated when the request URI is registered MUST be validated by the time or at the time when the request URI is used.

I'd perhaps word it more like:

> Servers MUST ensure that all parameters to the authorization request are still valid at the time when the request URI is used.

as some parameters may have changed in-between creation and use of a request object, depending on exactly how "should be short-lived" is interpreted. How realistic it is to make attacks based on that is perhaps debatable.

**Comment by tlodderstedt** [comment]
> Yes, but this then requires people to customise both the PAR endpoint and the authorisation endpoint. Existing plugins that do validation at the Authorization Endpoint will often assume that additional context is available, including (but not limited to) the end user's IP address, session cookies and user identity.

If I would use custom parameters and wanted to get the most out of PAR , I would indeed customize the PAR endpoint behaviour to get an early refusal of the request. 

> Servers MUST ensure that all parameters to the authorization request are still valid at the time when the request URI is used.

So the combined clause would read 

The AS SHOULD validate the request in the same way as at the authorization endpoint. The AS MUST ensure that all parameters to the authorization request are still valid at the time when the request URI is used.

**Comment by panva** [comment]
wfm

**Comment by b---c** [comment]
Alternative wording suggested by Vladimir at https://mailarchive.ietf.org/arch/msg/oauth/Lz6kWcdZP5lD1hVE6b8l3Ez6fQw, which I think has the same meaning and reads a little better:  

> "The AS MUST validate the request in the same way as at the authorization endpoint, or complete the request validation at the authorization endpoint."

**Comment by b---c** [comment]
More on that thread with maybe some consensus forming around proposed wording from @tlodderstedt and Annabelle: https://mailarchive.ietf.org/arch/msg/oauth/IMzK_U87xLDOecfDMl3j6aVIL5w

**Comment by jogu** [comment]
Thanks Brian. The latest proposal on that thread looks good to me (and addresses my previous concerns), to copy the suggestion (Annabelle's, with Torsten's suggested tweak):

> For the text in Section 2.1:
>  
> 3.  The AS MUST validate the pushed request as it would an authorization
>     request sent to the authorization endpoint, however the AS MAY omit
>     validation steps that it is unable to perform when processing the
>     pushed request.
>  
>  
> Additional text for Section 4 (note that this section pertains to the authorization endpoint):
>  
> The AS MUST validate authorization requests arising from a pushed request as
> it would any other authorization request.  The AS MAY omit validation steps
> that it performed when the request was pushed, provided that it can validate
> that the request was a pushed request, and that the request or the authorization server’s policy has not been modified in a way that would affect the outcome of the omitted steps.

**Comment by b---c** [comment]
PR #49 incorporates the  latest proposal

**Comment by b---c** [comment]
PR #49 was merged and this should/will be in -02
