### ISSUE TITLE
Can an AS require JWT rather than JSON?

### ISSUE THREAD

**Issue by davidgtonge** [oauthstuff/draft-oauth-par#4]
The current text lets the client decide, but an AS may want to require JWTs to be sent, should this be supported?

**Comment by b---c** [comment]
It's JWT or form encoded params (not JSON).

**Comment by b---c** [comment]
But I'm inlined to say that an AS might have some policy as such but I don't think there's a need to have metadata or whatever to try and express that.

**Comment by davidgtonge** [comment]
Thanks, you are right I mean form encoded vs jwt.
I agree that metadata is probably overkill for this

**Comment by tlodderstedt** [comment]
Could the fact that the client set up request object signing alg be the trigger for enforcing request objects?

**Comment by panva** [comment]
We already use that to ensure the request/_uri or PAR in any mode must be used by the client.

Not specifying it to allow for the simple mode also allows regular auth requests.

**Comment by tlodderstedt** [comment]
You mean the same client can use regular authz requests and request objects in parallel?

**Comment by panva** [comment]
> You mean the same client can use regular authz requests and request objects in parallel?

When request_object_signing_alg is not set, yes.

**Comment by panva** [comment]
https://bitbucket.org/openid/connect/issues/1045/signalling-that-a-request-object-must

**Comment by tlodderstedt** [comment]
@panva the OIDC ticket is still open, so I assume no decision has been met yet?

**Comment by panva** [comment]
It has. Errata will clarify that request_object_signing_alg forces request objects to be used. 

https://bitbucket.org/openid/connect/issues/1045/signalling-that-a-request-object-must#comment-49327844

**Comment by tlodderstedt** [comment]
thanks. Seems I didn't see the "We will clarify that this is the intended usage in the errata edits."

**Comment by b---c** [comment]
I think these two PRs on JAR would define the metadata for this https://bitbucket.org/Nat/oauth-jwsreq/pull-requests/5 and https://bitbucket.org/Nat/oauth-jwsreq/pull-requests/6 and @tlodderstedt has indicated he'd thinks "we should mention that the JAR metadata are in effect for PAR as well"

**Comment by b---c** [comment]
raft-ietf-oauth-jwsreq-25 introduced require_signed_request_object and the following commit e30501875a43e84a45716dc7ac134e14cdcb031e adds a note to PAR about it
