### ISSUE TITLE
request_uri must refer to JWT

### ISSUE THREAD

**Issue by tlodderstedt** [oauthstuff/draft-oauth-par#40]
That’s what JAR says. PAR deviates from this definition since the request_uri is produced and consumed by the AS.

Annabelle proposed to add the following text to PAR:

As defined in [JAR], the request_uri parameter is required to reference a Request Object JWT. An AS MAY violate this requirement when it is generating request URIs intended for its own consumption (e.g., URIs for pushed requests). This requirement exists to ensure interoperability in cases where the provider of the request_uri is a separate entity from the consumer, such as when a client provides a URI referencing an object stored on the client’s backend service. When the AS is both provider and consumer, this interoperability concern does not apply.

**Comment by b---c** [comment]
Maybe it'll be addressed in JAR https://mailarchive.ietf.org/arch/msg/oauth/91ihk0M_WTsdXgSigIm5VPozMc4/

**Comment by tlodderstedt** [comment]
https://tools.ietf.org/html/draft-ietf-oauth-jwsreq-22 resolves this issue
