### ISSUE TITLE
PAR and client and/or AS metadata

### ISSUE THREAD

**Issue by b---c** [oauthstuff/draft-oauth-par#43]
Thread at
https://mailarchive.ietf.org/arch/msg/oauth/OKUB5dkCwC1tDVknO0rVZYjbf-M/

**Comment by b---c** [comment]
Probably client. Maybe AS. IMHO. Didn't get addressed at virtual interim so need to get to rough consensus on the list. 


https://datatracker.ietf.org/meeting/interim-2020-oauth-05/materials/minutes-interim-2020-oauth-05-202004201200

**Comment by tlodderstedt** [comment]
In my opinion, AS is even more important. 

Sent a post to the list.

**Comment by b---c** [comment]
Later in the aforementioned thread @tlodderstedt has a more concrete proposal that IMHO is about right https://mailarchive.ietf.org/arch/msg/oauth/gkGm6rQxC3eCf8WjRGNsE_YTwHg/

**Comment by tlodderstedt** [comment]
PR #46

**Comment by b---c** [comment]
PR #47 is another attempt at this

**Comment by b---c** [comment]
PR #47 was merged and this should/will be in -02
