### ISSUE TITLE
Bring client_id back?

### ISSUE THREAD

**Issue by leastprivilege** [oauthstuff/draft-oauth-par#44]
in PAR-01 this example is used

```
GET /authorize?request_uri=
       urn%3Aexample%3Abwc4JK-ESC0w8acc191e-Y1LTC2 HTTP/1.1
``` 

but JAR-21 makes `client_id` mandatory.

Will PAR bring it back as well? 

IMO - it would be nice from an implementer point to always have the client_id required.

**Comment by tlodderstedt** [comment]
yes it will as part of #42

**Comment by leastprivilege** [comment]
ok thanks!

**Comment by tlodderstedt** [comment]
PR #45
