### ISSUE TITLE
Add text explaining one time use and need for integrity protection

### ISSUE THREAD

**Issue by tlodderstedt** [oauthstuff/draft-oauth-par#53]
Neil raised these topics on the list
* one time: PAR contains one time use parameters, such as code_challenge, state, or nonce
* integrity: attackers can modify request data to swap the context (pay my stuff) or change requirements defined by the client (e.g. acr values, assurance requirements regarding end user claims) and so on. clients can detect such changes after the fact by checking the outcome of the transaction. However, preventing modification is simpler and adds another layer of defense.

**Comment by tlodderstedt** [comment]
PR #56 should resolve this issue.

**Comment by b---c** [comment]
feaa1ee3eaeee1e855e243609e4b46b2fd7f40fa 07fd74de34001547ddb6fdf031bdb24bcfc6b4df 5a888546c048f913350293136e7455d7c72e207c 9574ebcc45bd1db6fe8760fc9cd6d0aefbb1b7fe
