### ISSUE TITLE
Add text on PAR alternatives and advantages

### ISSUE THREAD

**Issue by tlodderstedt** [oauthstuff/draft-oauth-par#54]
it was brought up in the RAR session yesterday at the OSW 2020 that POST requests to the authz endpoint could be used to cope with size limitations. That's a viable option for traditional web applications. It's difficult to use for mobile apps, since custom tabs and the like just open a certain URL with a GET request. Using POST would require the app to first open an own page and then initiate the form POST towards the AS. PAR is simpler to use.

Also the question was raised whether PAR makes sense for simple authorization requests. I think the client authentication improves security of any application since confidential clients cannot be spoofed.

**Comment by tlodderstedt** [comment]
see #57

**Comment by b---c** [comment]
f969d3e50c07ce3384cfe69ff65a714b065e0b13 and c18c7ece8a35c883a17fac86614381a35993a703
