### ISSUE TITLE
I'm unclear on the required behaviour for error responses

### ISSUE THREAD

**Issue by jogu** [oauthstuff/draft-oauth-par#59]
I'm having trouble figuring out how to parse this part of the spec:

> For an error the authorization server sets an appropriate HTTP status code and MAY include additional error parameters in the entity-body of the HTTP response using the format specified for the token endpoint in Section 5.2 of [@!RFC6749].

(from https://github.com/oauthstuff/draft-oauth-par/blob/master/main.md#error-response-error_response )

In particular I'm not sure if the 'MAY' means a json response is required or not.

I believe the intention is that the response is like the token endpoint, except not too explicit about what http status codes are used (I presume it imples any 4xx code?), I'd suggest the following wording:

> For an error the authorization server sets an appropriate HTTP status code and otherwise uses the format specified for the token endpoint in Section 5.2 of [@!RFC6749]. The authorization server MAY include additional error parameters in the entity-body of the HTTP response

(or perhaps the first sentence should have a 'MUST', not sure.)

**Comment by davidgtonge** [comment]
Hi Joseph,

I think you are right the wording could be improved, although I'm not sure about the use of "otherwise" - I'd leave that word out and I think it works.

**Comment by jogu** [comment]
I think that works, thanks Dave.

I'm also slightly confused by the next sentence:

> If the authorization server sets an error code, it SHOULD be one of
> the defined codes for the token endpoint in Section 5.2 or for the

In particular the 'if' part - I think RFC6749 5.2 requires an error code, so I'm not sure in what scenario an error response could not have an error code.

**Comment by b---c** [comment]
755d70cdee690e2e4c3199fbb5843c61752ee5de
