### ISSUE TITLE
Example around client_id doesn't seem to match JAR

### ISSUE THREAD

**Issue by jogu** [oauthstuff/draft-oauth-par#60]
https://tools.ietf.org/html/draft-ietf-oauth-par-01#section-4 says:

>    The client uses the "request_uri" value returned by the authorization
>    server as the authorization request parameter "request_uri" as
>    defined in JAR.
> 
>      GET /authorize?request_uri=
>        urn%3Aexample%3Abwc4JK-ESC0w8acc191e-Y1LTC2 HTTP/1.1

As per https://tools.ietf.org/html/draft-ietf-oauth-jwsreq-24#section-5 I think this example should include `client_id`.

**Comment by panva** [comment]
@jogu please use https://tools.ietf.org/html/draft-ietf-oauth-par-03
