### ISSUE TITLE
Typo in section 3 / use of imperative

### ISSUE THREAD

**Issue by kmzs** [oauthstuff/draft-oauth-par#65]
> The authorization server needs to take the following steps beyond the processing rules defined in Section 2.1:
> 1. If applicable, decrypt the request object as specified in JAR [I-D.ietf-oauth-jwsreq], section 6.1.
> 2. **Validates** the request object signature as specified in JAR [I-D.ietf-oauth-jwsreq], section 6.2.
> 3. If the client is a confidential client, the authorization server MUST check whether the authenticated client_id matches the client_id claim in the request object. If they do not match, the authorization server MUST refuse to process the request. It is at the authorization server's discretion to require the iss claim to match the client_id as well.

I think **Validates** in 2. should be changed to **Validate**; the imperative is used in 1., as well.

**Comment by b---c** [comment]
b576e771dd64d971d8891e6b9ae1f5a1c99aeaa0
