### ISSUE TITLE
Metadata if only PAR allowed

### ISSUE THREAD

**Issue by danielfett** [oauthstuff/draft-oauth-par#67]
When an OP does not support the request_uri parameter, it can set the metadata value `request_uri_parameter_supported` to `False`. This, however, also implies that PAR is not supported.

Is there a way to communicate that an OP supports PAR, but not the `request_uri` parameter with arbitrary URLs, for example, to avoid Server-Side Request Forgery?

**Comment by bc-pi** [comment]
I think a not-unreasonable argument could be made that `"request_uri_parameter_supported":false` along with a `pushed_authorization_request_endpoint` entry would convey that situation. The presence of a PAR endpoint kinda implies that the `request_uri` parameter with AS created URI values will be accepted. Otherwise PAR wouldn't work and that metadata would be a logical fallacy.

**Comment by TakahikoKawasaki** [comment]
If a server whose discovery document says

```
"request_uri_parameter_supported":false,
"pushed_authorization_request_endpoint":"...",
```

accepts `request_uri`, it looks odd, even if the server accepts only `request_uri` issued from the PAR endpoint.

An intuitive solution would be to define new server/client metadata, but I'm not sure it's worth doing it because we already have `require_pushed_authorization_requests` server/client metadata.

**Comment by danielfett** [comment]
> An intuitive solution would be to define new server/client metadata, but I'm not sure it's worth doing it because we already have `require_pushed_authorization_requests` server/client metadata.

In the case I'm thinking about, `require_pushed_authorization_requests` needs to be `false`. We would need something like `request_uri_must_be_pushed_authorization_request_uri` or, to save some bytes, `request_uri_par_only`.

**Comment by panva** [comment]
I don't think we need any such new metadata, presence of `pushed_authorization_request_endpoint` is enough for a client to know it may use PAR. How an AS handles `request_uri_parameter_supported` is fine for me to be left up to the implementer. Some implementers may want to tie in PAR to an enabled request uri support where they "just handle the request object storage", some will want to circumvent existing pipelines and expose just PAR.

> presence of `pushed_authorization_request_endpoint` is enough for a client to know it may use PAR

I suggest we mention this in the specification.

**Comment by TakahikoKawasaki** [comment]
What I questioned in my previous comment was whether the use case is common and broad enough to be worth adding new server/client metadata in addition to `require_pushed_authorization_requests`. I understand that `require_pushed_authorization_requests` is different from what Daniel exactly wants.

But because I'm not a security expert, to be honest, I cannot judge how important the use case is. I have no strong feeling to support or not, but I felt that discussion and consensus in the community would be needed.

**Comment by panva** [comment]
> Is there a way to communicate that an OP supports PAR, but not the request_uri parameter with arbitrary URLs, for example, to avoid Server-Side Request Forgery?

to answer daniel's original question. Yes, there is. An op may support request uris, par, but may indicate a pre-registration requirement of used uris with 

> require_request_uri_registration
> OPTIONAL. Boolean value specifying whether the OP requires any request_uri values used to be pre-registered using the request_uris registration parameter. Pre-registration is REQUIRED when the value is true. If omitted, the default value is false.

**Comment by danielfett** [comment]
@panva Wouldn't this, strictly speaking, imply that the client would have to register each individual PAR URI?

**Comment by panva** [comment]
@danielfett that would be taking the normative language to the extreme. No client using PAR can possibly think they need to turn to the AS with a request_uri it got from it to pre-register it. The protocol flow in PAR is clear. One can also consider the PAR returned request_uri already pre-registered.

**Comment by panva** [comment]
My suggestion here would be to come up with two simple guidance notes

1) presence of `pushed_authorization_request_endpoint` is enough for a client to know it may use PAR. Other AS metadata presence is not required.
2) PAR-returned `request_uri` is usable regardless of the AS metadata `require_request_uri_registration` value.

**Comment by bc-pi** [comment]
+1 to what @panva said but I'd say that 2. should be a little more inclusive with something more like "... regardless of other AS metadata such as `request_uri_parameter_supported` or `require_request_uri_registration`"

**Comment by panva** [comment]
@bc-pi SGTM

**Comment by tlodderstedt** [comment]
sgtmaw :-)

**Comment by TakahikoKawasaki** [comment]
```
[Request URI Support]
  |
  +- Not Supported (request_uri_parameter_supported == false)
  |
  +- Supported (request_uri_parameter_supported == true)
        |
      [PAR Support]
        |
        +- Not Supported (pushed_authorization_request_endpoint == null)
        |
        +- Supported (pushed_authorization_request_endpoint != null)

[Request URI Requirement]
  |
  +- Optional
  |     |
  |   [PAR Only]
  |     |
  |     +- No
  |     |
  |     +- Yes
  |
  +- Mandatory
        |
      [PAR Only]
        |
        +- No
        |
        +- Yes (require_pushed_authorization_requests == true) (<-- current meaning)
```

If we wanted to cover all the cases above orthogonally, what we need to do would be:

1. To create metadata that indicates whether `request_uri` is optional or mandatory.
2. To change the meaning of `require_pushed_authorization_requests` from _"request_uri is always required and it must be one issued from the PAR endpoint"_ to _"if request_uri is given, it must be one issued from the PAR endpoint"_.

FYI: The JAR specification has special metadata that claims the following.

```
[Request Object Processing Rule] == JAR       &&
[Request Object Requirement]     == Mandatory &&
[Request Object Signing]         == Mandatory

  --> require_signed_request_object == true
```

**Comment by b---c** [comment]
PR #68 attempts to capture the rough consensus regarding adding some simple guidance. 

We are past WGLC but have been waiting (for months) on Hannes to do the shepherd writeup. So I think we'll be fine to squeeze in an explanatory note in a new draft.

Barring any objections/corrections, I'll push out an -06 maybe later today or tomorrow.

**Comment by b---c** [comment]
33b9d09f0ff160ed511296dae41f2853e5b4a720
