### ISSUE TITLE
The client could register per-authorization request redirect URIs

### ISSUE THREAD

**Issue by tlodderstedt** [oauthstuff/draft-oauth-par#9]
Confidential clients could be given the option to register per-authorization request URIs. This gives such clients more flexibility (e.g. dynamically include an AS-specific element to detect mix-up).

**Comment by panva** [comment]
Why not, however - is there a signal from anyone asking for it?

**Comment by tlodderstedt** [comment]
IDP schemes with central client credentials management could utilize this. Right now, we are using a proprietary "iss" response parameter to indicate the AS/IDP since the client cannot use different redirect URIs for different ASs. 
With this feature, a client could dynamically set up a redirect URI containing a issuer specific part.

**Comment by tlodderstedt** [comment]
Same holds true for PSD2. In this case, the AS relies on 3rd parties (Certification Authorities) to authorize the clients and provide them with credentials (x.509 certs). There is no direct relationship before the first request hits the AS. Some solutions use dynamic registration for establishing local credentials, others (namely Berlin Group) establish the redirect URI in the first request, when the lodging intent is created.
PAR with dynamic registration of the redirect URL would be a good alternative.

**Comment by tlodderstedt** [comment]
oh, I just remembered another limitation in PSD2. There is no redirect URI managed by the regulatory infrastructure, just certificates conveying the role of a TPP (e.g. AISP). 

Using PAR to establish this redirect URI is simple. 

Using dynamic client registration to achieve the same is more complex due to various reasons:
* RFC 7591 does only support initial access tokens as means to authenticate and authorize. It does not support client authentication via token endpoint authentication methods. This means a TPP having a eIDAS certificate needs to use a proprietary mechanism to set up a client account or to obtain an initial access token. 
* Even if the TPP manages to get the client credential it must manage it's lifecycle (or better put their lifecycle for all ASPSPs).
@davidgtonge how does this work in UK OB?

**Comment by davidgtonge** [comment]
@tlodderstedt sorry I missed this issue. I think this is a good addition. 
Dynamic client registration definitely has its problems and I think you are right that that this is an interesting solution. There are benefits to DCR though and I think where its possible to implement it is preferable. 

In the UK some ASPSPs issue their own set of credentials, but some just use mutual TLS based on eidas or equivalent certs.

**Comment by vdzhuvinov** [comment]
OAuth 2.0 required out-of-band agreement or client registration of the redirect_uri to prevent its tampering during the redirection to the AS .

But now, with the client submitting the authZ request directly, that's no longer required, unless the redirect_uris need to be locked down by some other authority.

If the client IDs and credentials are managed by some authority (CA or other type), the client registration could practically be skipped.

I find this an excellent idea and it's worth mentioning as a benefit of PAR.

**Comment by tlodderstedt** [comment]
change merged into master

**Comment by tlodderstedt** [comment]
merged PR
